.TH TINT2CONF 1 "April 25, 2011"
.\" Please adjust this date whenever revising the manpage.
.SH NAME
tint2conf \- tint configuration manager
.SH SYNOPSIS
.B tint2conf
.SH DESCRIPTION
tint2conf is a GTK based configuration previewer for tint2.
.SH OPTIONS
tint2conf takes no parameters.
.SH AUTHOR
tint2conf was written by the tint2 team.
.PP
This manual page was written by Sebastian Reichel <sre@debian.org>,
for the Debian project (but may be used by others).
